wake_word:
  model: openWakeWord
  wake_word: hey_jarvis
  end_word: alexa
  threshold: 0.5

stt:
  model: whisper
  model_id: openai/whisper-base.en

llm:
  model: pydantic-ai
  name: gemma4:e4b

tts:
  model: kokoro
  voice: af_bella
  # piper example:
  # model: piper
  # voice: en_US-lessac-medium
  # model_path: voices/piper/en_US-lessac-medium.onnx
